version: 2.1
commands:
  destroy_environment: 
      steps:
      - run:
          name: Delete the Stack created 
          command: |
            aws cloudformation delete-stack --stack-name my-stack
jobs:
  configure_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create infrastructure 
          command: |
             pwd && \
             ls -al && \
             aws configure set default.region us-west-2 && \
             aws configure set aws_access_key_id default_access_key && \
             aws configure set aws_secret_access_key default_secret_key && \
             aws cloudformation create-stack --stack-name my-stack --template-file template.yml            
  smoke_test:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout 
      - run: return 1
      - run:
          name: Delete the Stack created 
          command: |
             aws configure set default.region us-west-2 && \
             aws cloudformation delete-stack --stack-name my-stack
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
      - smoke_test: 
          requires: 
            - configure_infrastructure
