version: 2.1
commands:
  destroy_environment: 
      steps:
      - run:
          name: Delete the Stack created 
          command: |
            aws cloudformation delete-stack --stack-name my-stack
jobs:
  configure_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create infrastructure 
          command: |
             pwd && \
             ls -al && \
             aws configure set aws_access_key_id AKIA5KZXAHFUONFHFYGR aws_secret_access_key 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 region us-west-2
             
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
