version: 2.1
commands:
  destroy_environment: 
      steps:
      - run:
          name: Delete the Stack created 
          command: |
            aws cloudformation delete-stack --stack-name my-stack
jobs:
  configure_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create infrastructure 
          command: |
             pwd && \
             ls -al && \
             aws configure set aws_access_key_id "AKIA5KZXAHFUONFHFYGR" && \
             aws configure set aws_secret_access_key "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" && \
             aws configure set default.region us-west-2 && \
             aws cloudformation deploy --template-file template.yml --stack-name my-stack            
  smoke_test:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout 
      - run: return 1
      - run:
          name: Delete the Stack created 
          command: |
             aws configure set aws_access_key_id AKIA5KZXAHFUONFHFYGR && \
             aws configure set aws_secret_access_key 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 && \
             aws configure set default.region us-west-2 && \
             aws cloudformation delete-stack --stack-name my-stack
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
      - smoke_test: 
          requires: 
            - configure_infrastructure
